export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART = 'TOGGLE_CART';
export const ADD_ITEM = 'ADD_ITEM';
export const REDUCE_ITEM = 'REDUCE_ITEM';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
